# Generated by Django 3.1.3 on 2020-11-11 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание выбора')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('description', models.TextField(verbose_name='Описание опроса')),
                ('begin_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время начала')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 11, 12, 1, 28, 57, 971416, tzinfo=utc), verbose_name='Конец опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Описание вопроса')),
                ('type', models.CharField(choices=[('TXT', 'Text'), ('ONE', 'One choice'), ('MUL', 'Multiple choice')], max_length=3, verbose_name='Тип вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='ID пользователя')),
                ('text', models.TextField(verbose_name='Текстовый ответ')),
                ('choice', models.ManyToManyField(to='API.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.question')),
            ],
        ),
    ]
