# Generated by Django 3.1.3 on 2020-11-11 21:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201112_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текстовый ответ'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 1, 45, 14, 413373, tzinfo=utc), verbose_name='Конец опроса'),
        ),
    ]
